### ISSUE TITLE
Is there a commonjs version of this lib?

### ISSUE THREAD

**Issue by rajeshps** [spurushottam13/bifrost-cross#1]
Basically exports and promises are having issues.
Is there a transformed or compiled version of this lib to use in html page directly and not as module?

Also, to check and retrieve data of different domain (from localstorage) doesn't need initializing bifrost for both domains right?

Thanks.

**Comment by spurushottam13** [comment]
Unfortunately till now, it does not have but to gets things to work , 
you can copy the content of _index..js_ file expect this line `export default BifrostCors` in new js file of your project and add to your HTML

**Comment by rajeshps** [comment]
Hi,
Thanks for quick response, I tried once but hit some blockers with promises never resolving - will give it another try and revert.

What about the initializing case where real-time interaction b/w domains isn't needed only to get and set data in localstorage.

Thanks.

**Comment by spurushottam13** [comment]
Hi,
I think the promise is not resolving maybe because you accessing the API before lib loads the other domain, can you try initializing the lib at very early before using its methods, (actually lib loads the other domain in an iframe and after then only it works), you can initialize the lib with any small size page (which will load faster)

and about the second part of the comment, I really didn't get you what you asking

**Comment by rajeshps** [comment]
Hi, yes looks like the case what you highlighted, I'll move this to initialize early.

About second part, was trying to understand in what scenario "initialize in both domain" needed?

**Initialize Bifrost-CORS You have to Initialize Bifrost-CORS in both domain** - from the readme.

Thanks.

**Comment by rajeshps** [comment]
Hi, couldn't get through the promise issue.
is the below usage the right way? or you see anything wrong with this?

```
<!-- loaded this script in https://www.exampleA.com -->
<script src="/js/bifrost.js"></script>
<script>
window.addEventListener("DOMContentLoaded", function() {
  var bifrostCors = new BifrostCors("https://exampleB.com/",false);
  var cookies = bifrostCors.getCookie();
  console.log("cookies retrieved", cookies); // this is pending promise

  // tried this as well
 // var cookies = bifrostCors.getCookie().then((data) => {
 //	console.log(data); // this too is pending promise
 // }); 

}, true);
</script>
```

**Comment by spurushottam13** [comment]
Hi you have to initialize lib in both domains (not just include)


**In exampleA.com** 

```
<script src="/js/bifrost.js"></script>
<script>
var bifrostCors = new BifrostCors("https://exampleB.com/",false);
</script>
```


**In exampleB.com** 

```
<script src="/js/bifrost.js"></script>
<script>
var bifrostCors = new BifrostCors("https://exampleA.com/",false);
</script>
```

**Comment by rajeshps** [comment]
Thanks for the hint, will add to both domains and try. 
In fact my second part of earlier question was about the same.

**Comment by spurushottam13** [comment]
Happy to help you : ),
I am closing this issue, open it again if required

**Comment by cax111** [comment]
hei... can you provide an example of this library for vuejs ? cause i have a similiar problem with this issue, in my vuejs project the promise always pending, i put the code in main.js.
Thanks in advance...
