### ISSUE TITLE
What about multiple sites?

### ISSUE THREAD

**Issue by zehawki** [spurushottam13/bifrost-cross#4]
You've mentioned address = Exact Address of the other domain

What if there are multiple addresses to access from, ie a single hub with multiple clients like https://www.npmjs.com/package/cross-storage

**Comment by spurushottam13** [comment]
Sorry currently it does not support multiple client using one instance
you will require to create separate instance of Bifrost for each client in hub

**Comment by zehawki** [comment]
Hey thanks for the quick response. I ended up integrating the above package, working like a charm for now.
